version: "3.7"

services:
  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: docker_northcoders_news
    ports:
      - "5433:5432"
    volumes: 
      - backup:/var/lib/postgresql/data


  express_server:
    build: .
    environment:
      - NODE_ENV=docker
      - HOST=database
    depends_on:
      - database
    ports:
      - "9090:9090"


volumes: 
  backup:


